### ISSUE TITLE
Syncing with data store

### ISSUE THREAD

**Issue by chimon2000** [jxom/react-loads#14]
I currently am using this library, and we use Context (via [Constate](https://github.com/diegohaz/constate)) in several places in the application to manage state.  

Is it possible to update a data store with the result of the react-loads request?  Currently, when I attempt to do something similar I get an **Invariant Violation**.

Example: https://codesandbox.io/s/3yqqzkxrq5

I was looking for something similar to `afterFetch` in [react-request](https://github.com/jamesplease/react-request)

**Comment by jxom** [comment]
FYI, I just added [this example](https://codesandbox.io/s/4j2q7j2xw9) to the readme, which looks kind of similar to what you're trying to achieve. But if you still want to user the response, you can just intercept the `fetchCharacters` method in `CharacterList`. Hope it's helpful!

**Comment by chimon2000** [comment]
Thanks for the quick response and the updated example!  For my case, I was looking to be able to mutate the data after it's loaded.  

After reading your comments, I realized that I could also accomplish this by just making GetUsers a regular class component with any mutation / state operations that I need.  It doesn't have to be Context.

**Comment by jxom** [comment]
If you want to modify the response from the server, just modify it and return it in the loading function, and that will be the data to be cached.

**Comment by jxom** [comment]
(it doesn’t cache the data coming from axios, it caches the data returned from the loading function)

**Comment by jxom** [comment]
I’m gonna close this now, but just reply if you have any questions

**Comment by jxom** [comment]
Hey @neoighodaro, can you share your usage? Shouldn’t be happening...

**Comment by neoighodaro** [comment]
I found a way around it. I had to wrap `await this.$ref.checkoutRef.open()` around a `setTimeout` call. So I guess that's the hack around it.

However, look at the example you provided to see the issue. It doesn't pick up the changes until the second checkout popup.


________________________________
