### ISSUE TITLE
Doesn't work with React Native

### ISSUE THREAD

**Issue by dannief** [jxom/react-loads#2]
This is the best abstraction around promises that I've tried so far. Only issue is, is that it doesn't work with React Native, at least out of the the box. I get an error that it can't find module 'path'. Digging deeper, I see that this is due to react-loads' dependency of react-automata, which in turn depends on minimatch, which uses the node build in package 'path'.

I am very new to React Native, but apparently React Native cannot compile native npm packages. I have seen where I can probably get around the problem by installing the 'path' npm package manually. Apparently this is equivalent to the built in npm module, at least it was 3 years ago when the package was last updated. I haven't tried it because I didn't want to go down the road of installing extra packages for such relatively small library. I did want to bring it to your attention to see what you think. If you never had any intention of supporting React Native, then I suppose you can close this issue. I also realize that this is not directly an issue of the library but a dependency , but perhaps you would like to know and at least add it to the documentation.

Thanks

**Comment by jxom** [comment]
Hey Dannief.

Sorry to hear that you are having trouble getting this set up with React Native. 
React Loads *should* work with any React renderer whether it be react-dom, react-native, react-tv etc... but then again, I’ve only tested it myself with the browser. 

I’ll have a look into this when I have the time. If anyone else wants to check this out, then that will be great!

**Comment by jxom** [comment]
@dannief, can you please comment with the error output you are receiving? That would help heaps!

**Comment by jxom** [comment]
Expo seems to deal with it fine: https://snack.expo.io/@jxom/react-loads

I might need to manually do it though, I just don't wanna download all

**Comment by dannief** [comment]
@jxom I had removed the code, but will add it back and copy the error message when I find some time later.

Note though, that I didn't create my project using Expo or CRNA. I used the `react-native init` command, if that makes any difference. I am also running on windows and testing on an Android device.

**Comment by dannief** [comment]
Finally find some time to test this again. See the error stack below.

```
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `path` from `C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\minimatch\minimatch.js`: Module `path` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:161:1460)
    at ResolutionRequest.resolveDependency (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\node-haste\DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\DeltaBundler\traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\DeltaBundler\traverseDependencies.js:374:16)
    at C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\DeltaBundler\traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:313)
    at C:\Dev\Personal\Tutorials\reactnative\manager\node_modules\metro\src\DeltaBundler\traverseDependencies.js:297:473
```

**Comment by superKalo** [comment]
@jxom I used your example: https://snack.expo.io/@jxom/react-loads It doesn't work via the Snack url either.

**Comment by jxom** [comment]
Looks like @auzwang got this working in React Native, I think the `react-automata` package update fixed it. - so I'm going to close this for now.
