### ISSUE TITLE
Function to determine how the context should update? 

### ISSUE THREAD

**Issue by dwjohnston** [jxom/react-loads#22]
Let's say I have an API that looks like this: 

```
export const getTodos = async (): Promise<Todo[]> => {
    return await new Promise((res, rej) => {
        setTimeout(() => {
            res(initialTodos);
        }, 2000)
    });
}

export const postTodo = async (value: string): Promise<Todo> => {
    return await new Promise((res, rej) => {
        setTimeout(() => {
            res({
                id: `${Math.random()}`, 
                value, 
            });
        }, 2000)
    }); 
}
```

That is - getting the todos will return an _array_ of Todos, while posting a Todo returns a single Todo (with the ID generated). 

Now in one component I want to display the Todos, easy enough: 

```
export const ThingyA: React.FunctionComponent<ThingyAProps> = (props) => {
    const {
       
    } = props;
    const doGetTodos = React.useCallback(getTodos,[]); 
    const { response , error, load, isIdle,  isRejected, isPending, isResolved } = useLoads(doGetTodos, {
        context: "todos", 
    });

    return <div >
      <h2> View Todos</h2>

        {isIdle && <p> Idle</p>}
        {isPending &&  <p>...loading</p>}
        {isResolved && <ul>
                {response.map((todo:  Todo) => <li>{todo.value} </li>)}
             </ul>}
    </div>;
}
```

And in the other, I want to submit a Todo: 

```
export const ThingyB: React.FunctionComponent<ThingyBProps> = (props) => {
  const {

  } = props;

  const doPostTodo = React.useCallback(postTodo, []);
  const { response, error, load, isIdle, isRejected, isPending, isResolved } = useLoads(doPostTodo, {
    defer: true,
    context: "todos"
  });
  const [value, updateValue] = useState('');

  return <div >
    <h2> Thingy B</h2>

    <form onSubmit={(e) => {
      e.preventDefault();
      load(value);
    }}>
      <input value={value} onChange={(e) => updateValue(e.target.value)} />
      <button type="submit"> submit</button>
    </form>
  </div>;
}
```
The problem with this code as it currently is, is that `ThingyA` expects a list of Todos and so it fails. 

Is there an option somewhere that I'm missing that configures how the context will update? (Something like a redux reducer). I'm curious how you would otherwise solve this problem. 

Code for this example here: https://github.com/dwjohnston/react-loads-play/tree/feature/CRUD

**Comment by jxom** [comment]
I see what you mean, maybe it will be nice to expose a `record` attribute on the last parameter of the loading function, which retrieves the current record from the context (if it exists):

```jsx
const postTodo = async ({ cachedRecord }) => {
  const newTodo = ...
  return [...cachedRecord.response, newTodo]
}
```

**Comment by dwjohnston** [comment]
Yeah, I'm thinking something like a `reducer` option. 

ie. where I'm creating a todo: 
```
 useLoads(doPostTodo, {
    defer: true,
    context: "todos", 
    reducer: (existingContext, response) => ([...existingContext, response])
  });
```

**Comment by jxom** [comment]
I kind of wanted to avoid using a 'reducer' as it involves another responsibility. I think the `cachedRecord` in the loading function arguments should be fine and suitable as it sits beside `setResponse` & `setError` - and it was also [just a one line change](https://github.com/jxom/react-loads/commit/07b50c0581a3e93df3e52ff86db46335c82becc1#diff-b192d837f32d97a1db7ca338370555ebR154).
