### ISSUE TITLE
Basic cache /context example doesn't seem to work

### ISSUE THREAD

**Issue by andycloke** [jxom/react-loads#27]
sorry if I'm missing something dumb, but as I understand it if I use the 'basic caching' example the network request shouldnt be made a second time. I used the exact example from here https://github.com/jxom/react-loads#basic-cache

`"react-loads": "^8.3.4",`
` "axios": "^0.19.0",`
`"typescript": "3.5.3"`

and the network request is made each time, i.e. it's not cached:
![Screenshot 2019-07-12 at 14 29 00](https://user-images.githubusercontent.com/21224310/61131558-732ce700-a4b1-11e9-864f-dd42fd1d31f9.png)

**Comment by andycloke** [comment]
I missed this. doh! https://github.com/jxom/react-loads#firstly

**Comment by jxom** [comment]
Maybe I should make this more clearer in the docs! :)
