### ISSUE TITLE
Switching context should abort the previous 'useLoads' request. 

### ISSUE THREAD

**Issue by dwjohnston** [jxom/react-loads#29]
Related to #28 . 

I updated to `8.3.7` and that solves that issue. 

But the issue now is: 

1. Select first item, works as expected (shows loading, then displays data). 
2. Select second item, works as expect (shows loading, then displays data). 
3. Select first item again, works as expected (display data from cache). 
4. Quickly select second item, it shows the second item from cache, but then the load response from the first item kicks in and overrides it.  

What should be happening, is that on subsequent calls of `useLoads` the previously running query should be aborted.

**Comment by dwjohnston** [comment]
Now using the `cache-first` loadPolicy will solve this (as it will never attempt to do the subsequent load), but you can imagine a scenario where you do want to subsequent loads (ie. displayed the cached version while you're waiting to see if it has updated on the server).

**Comment by jxom** [comment]
Can you update to `8.3.8`? That should fix it :)
