### ISSUE TITLE
How to use this library with class components (resources etc)?

### ISSUE THREAD

**Issue by CarlQLange** [jxom/react-loads#30]
Hey,

Thanks for the useful library.

My application is made up mostly of class components, and unfortunately hooks don't work within class components. I'm wondering how best to use this library, particularly the caching/resources functionality, with class components.

Thanks!

**Comment by jxom** [comment]
Hey! Glad to hear you've found it useful.

You can sure use React Loads with class components! Check out the example of [Render Props Usage](https://github.com/jxom/react-loads#with-render-props). The Render Props version of React Loads also shares the same API as the `useLoads` hook. 

`<Loads fn={fn} {...props}>` === `useLoads(fn, props)`

**Comment by CarlQLange** [comment]
OK, thanks! Unfortunately I'm still a beginner with React - perhaps if you could give a breakdown of what you think would need doing for that implementation, I could give it a go! Resources seems useful mostly due to the built-in caching, but I like the paradigm in general.
