### ISSUE TITLE
useLoadsCache does update on 'isPending' and does not return 'isPending' status

### ISSUE THREAD

**Issue by dwjohnston** [jxom/react-loads#35]
Sorry for not posting a full repro, but here's my issue: 

Somewhere I am submitting a form with this: 

```
    const loadsPackage = useLoads(registerUser, {

        defer: true,
        context: 'register',
        loadPolicy: "load-only", 
        enableBackgroundStates: true, 
    });
```

And then at the application root I want to access the 'isPending' state to set the loading cursor, 

```
  const register = useLoadsCache('register'); 
  useEffect(() => {
    console.log(register); 
  }); 
```

What I get is a response like this: 

```
"{"response":{"hasError":true,"error":{"type":"form","errors":{"url":"Sorry, this URL is taken"}}},"state":"resolved"}"
```

And this only occurs on resolution, not when it changes to `isPending`.

**Comment by jxom** [comment]
At the moment, React Loads only caches the resolved/rejected value. I'm not really keen on adding in caching for the other states just yet as this will be a burden on React Loads' performance. In the future, I want to [split React Loads context](https://github.com/facebook/react/issues/15156#issuecomment-474590693) to improve performance & scale React Loads which will in-turn allow me to add in caching for every state change in a context.
