### ISSUE TITLE
Typescript complains when using State Components

### ISSUE THREAD

**Issue by CarlQLange** [jxom/react-loads#37]
I can't use state components like `<Loads.Pending>` in my typescript app :(

Given something like the example: https://github.com/jxom/react-loads/blob/aef1779559feab3da9ae70978a6f74be183358a8/src/__stories__/index.stories.js#L528-L555, the compiler complains saying `Type 'Element[]' is not assignable to type '(loader: any) => ReactNode'.` - meaning that the `<Loads>` component expects its `children` to be a function only.

I think the related line is here: https://github.com/jxom/react-loads/blob/7badb872a4484e7111fec12d6bcb71faa4f2f2d7/src/Loads.tsx#L8 and maybe needs to be extended to add `Element[]` as a possible type.

**Comment by jxom** [comment]
Going to close this issue as state components have been removed in v9
