### ISSUE TITLE
When suspense: true error is not being thrown

### ISSUE THREAD

**Issue by Kamahl19** [jxom/react-loads#44]
I am using this with the suspense mode however my ErrorBoundary is not catching the error. I believe it's because of this line https://github.com/jxom/react-loads/blob/29419b235805fbb9310c04dd4fc98b7bc7fce7fd/src/useLoads.ts#L343

Why `if (throwError && !suspense)` ? Shouldnt it be `if (suspense)`? or `if (throwError)`

Currently I am using workaround and throwing error manually in component like
```
if (error) {
    throw error;
  }
```

**Comment by jxom** [comment]
Hey! Thanks for raising this - it is indeed a bug. Can you update to `9.1.1` and try this again?

**Comment by Kamahl19** [comment]
@jxom Hey, it's working great however now `throwError` is being ignored in suspense. I am unable to disable throwing when using suspense for special case. Could you please also check if `throwError` is true before throwing in suspense? Also default vault of `throwError ` should be true if suspense is on
