### ISSUE TITLE
When context changes but variables don't, the fetch function is not called

### ISSUE THREAD

**Issue by riosn-n** [jxom/react-loads#46]
I'm using context as an array. When one of the values in the context changes, but the parameters/variables remain the same. The "load" function doesn't get called.

**Comment by jxom** [comment]
Hey - the `context` parameter can only take form of a `string`. May I understand your use case for using an array?

**Comment by riosn-n** [comment]
Thanks for the quick reply. The issue is not related to array vs string. It occurs when "context" changes but the variables stay the same. Please try the code below with and without the "variables" parameter:

> import * as Loads from "react-loads";
> 
> const loadFn = () => {
>   console.log("Loading");
>   return Promise.resolve("resolved value");
> };
> 
> function App() {
>   const [context, setContext] = React.useState<string>("");
> 
>   const { response } = Loads.useLoads(context, loadFn, {
>     variables: ["abc"],
>   });
> 
>   return (
>     <div>
>       <input
>         type="text"
>         value={context}
>         onChange={(ev) => {
>           if (ev.target.value !== context) {
>             setContext(ev.target.value);
>           }
>         }}
>       />
>       Value: {response}
>     </div>
>   );
> }

**Comment by riosn-n** [comment]
Have you had a chance to look into this?
