### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by chimon2000** [jxom/react-loads#9]
It would be nice to have support for typescript definitions.

**Comment by jxom** [comment]
This would be nice!

**Comment by jxom** [comment]
Fixed in v7!

**Comment by natsukagami** [comment]
It seems that the published package does not include TypeScript declarations. I currently don't know why...

**Comment by jxom** [comment]
Hey @natsukagami, can you please update to `7.0.1` - forgot to include `ts/` folder in the NPM registry.
